apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-service-config
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:h2:mem:transactiondb
        username: sa
        password: 
        driver-class-name: org.h2.Driver
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
          ddl-auto: update
        show-sql: false
      h2:
        console:
          enabled: true
          path: /h2-console
    server:
      port: 8080
    logging:
      level:
        root: INFO
        com.hsbc.transaction: DEBUG
    springdoc:
      api-docs:
        path: /api-docs
      swagger-ui:
        path: /swagger-ui.html
    cache:
      type: caffeine
      caffeine:
        spec: maximumSize=500,expireAfterWrite=600s 